version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-claims
    ports:
      - "5025:5432"
    environment:
      POSTGRES_DB: claims_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend-claims
    ports:
      - "3057:3057"
    depends_on:
      - postgres
    volumes:
      - ./Backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development

  frontend:
    build: ./Frontend
    container_name: frontend-claims
    ports:
      - "8079:80"

  hr:
    build: ./HR
    container_name: hr-claims
    ports:
      - "8080:80"

volumes:
  postgres-data:

